version: '3.3'

services:
  db:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_DATABASE: linebot
      MYSQL_USER: ${DB_LINEBOT_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_LINEBOT_MYSQL_PASSWD}
      TZ: 'Asia/Tokyo'

  python:
    build: ./python3
    volumes:
      - ./python3:/work
    expose:
      - "3031"
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "80:8000"
      - "443:443"
    links:
      - python
    depends_on:
      - python