# Generated by Django 2.2.8 on 2019-12-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation_length',
            fields=[
                ('translation_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('year_month', models.CharField(max_length=6, unique=True, verbose_name='年月')),
                ('translation_length', models.IntegerField(verbose_name='翻訳文字数')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
    ]
